### PR TITLE
fix(rest-api-model-sever): make runnable with Kotlin 1.9

### PR DESCRIPTION
**Pull request by odzhychko**

### CODE REVIEW

**Review by languitar — COMMENTED** [review]
When I was using Quarkus more actively, I sometimes have seen issues, mostly in the developer tooling, when using a different kotlin version than defined by Quarkus. Therefore, I am not sure if it is a good idea to enforce something different than what Quarkus supports. The developer tools do some weird byte code magic sometimes to support hot reloading and so on. That easily breaks on other kotlin versions.

**Comment by odzhychko** [comment]
As far as I understand, our `modelix.core/model-client` needs the Kotlin's stdlib 1.9. Correct me, if I am wrong.

The changes in this PR make the example project at least runnable again.

When a Quarkus version with Kotlin 1.9 is released, we should of course upgrade it properly.
see. https://github.com/quarkusio/quarkus/commit/23db3bd9e65b98b5b5f23ee18103a4d2901b0ec3

I see three options:
* (A) Change nothing. Let the samples not run until we have Quarkus with Kotlin 1.9 support.
* (B) Accept the changes in the PR. Let the samples run, but with potential development problems.
* (C) Change the `model-client' to be usable with a lower version of Kotlin. 

I prefer (B) to (A), because at least the samples are runnable.
(C) would probably be ideal, but I am not sure if it is worth the effort.

**Comment by slisson** [comment]
Alternative solution provided in https://github.com/modelix/modelix.core/pull/207. Just update the modelix.core version once that change is released.

**Comment by languitar** [comment]
Not enforcing users of modelix to use the most recent kotlin versions sounds like the best option to me as well.

**Comment by languitar** [comment]
As a side note, we should still document why we are on a certain version here and maybe there are also ambiguities here in the project config that still need to be sorted out.

**Comment by odzhychko** [comment]
Using the new Modelix version in https://github.com/modelix/modelix.samples/pull/135

**Comment by odzhychko** [comment]
>   maybe there are also ambiguities here in the project config that still need to be sorted out.

@languitar Do you have anything specific in mind, that we should look into?

**Comment by languitar** [comment]
I wasn't sure if https://github.com/modelix/modelix.samples/blob/dcb1b450b26bebc2e9622acf81d03cd3fc15d467/gradle/libs.versions.toml#L80 with the version from the libs file (1.9) is automatically overridden by the bom. Or do we need to enforce a different version here?

**Comment by languitar** [comment]
Alright, not it is only slightly confusing still but technically correct. Maybe we can add some comment to the build file that, as desired, the bom wins here?

**Comment by odzhychko** [comment]
Sure, good idea. I opened a PR https://github.com/modelix/modelix.samples/pull/137

**Pull request closed without merging**
