### PR TITLE
feat(doc): update and simplify system diagram

### PR DESCRIPTION
**Pull request by nkoester**

### CODE REVIEW

**Comment by odzhychko** [comment]
image

I like the diagram very much. I find in much cleaner as the previous.

a) to e) are just visual details

f) Is it on purpose, that `rest-api-model-ql` read/writes from the model-server and not from MPS? Do you have in mind for as to change the sample in the future?

g) I do not understand the name Domain-Specific API. I see where you are coming from, but I would probably have named the boxes `Dashboard backend`. And on the connection to the Dashboard frontend, I would have written `read/write \n application-specific API \n (REST / Websocket)`.

Domain-specific API is very close to Domain-specific-language API.

**Comment by odzhychko** [comment]
For the Vue.js application, I would call the user `tutor` because it is more consistent with the naming in our metamodel.

For the Angular Dashboard (use case 3) I add a second user `tutor` because the dashboard can also write data.

**Comment by nkoester** [comment]
> f) Is it on purpose, that `rest-api-model-ql` read/writes from the model-server and not from MPS? Do you have in mind for as to change the sample in the future?
Prospectively the Kotlin based API will  be migrated to modelQLv2. In combination with the new model-server plugin for MPS any UC can be realized by using MPS "as a backend". I find it confusing to add more crossing arrows here and would rather got with this simple depiction alongside a not that the new plugin can act as a in-place replacement during development.

 
> g) I do not understand the name Domain-Specific API. I see where you are coming from, but I would probably have named the boxes `Dashboard backend`. And on the connection to the Dashboard frontend, I would have written `read/write \n application-specific API \n (REST / Websocket)`.
> 
> Domain-specific API is very close to Domain-specific-language API.

I understand your concerns - we already discussed a lot about this. Ultimately, the generated artifacts are indeed an API for the domain-specific language, hence `DSL API`. Proposal: Keep the naming but also add 'backend' to be clear of the function of that box?

**Comment by odzhychko** [comment]
f) 

> Eventually the Kotlin based API will be migrated to modelQLv2. In combination with the new model-server plugin for MPS any UC can be realized by using MPS "as a backend". I find it confusing to add more crossing arrows here and would rather got with this simple depiction alongside a not that the new plugin can act as a in-place replacement during development.

Ok, now I understand the reasoning.

g)

Just to confirm, we talk about the same thing.
The name "DSL API" is fine for the generated artifacts from the metamodel by modelix.
I had a (slight) issue with the name "Domain-specific API" on the Quarkus and KTor server.
I like your proposal to add backend to it, to make it clear.

**Pull request merged**
