### PR TITLE
Fx CVE 1050 and CVE 400

### PR DESCRIPTION
**Pull request by benedekh**
Fixes:
- https://github.com/modelix/modelix.samples/security/dependabot/32
- https://github.com/modelix/modelix.samples/security/dependabot/33
- https://github.com/modelix/modelix.samples/security/dependabot/34

### CODE REVIEW

**Comment by odzhychko** [comment]
Adding the dependency to braces explicitly seems to be the wrong way.
I think only the version in package-lock.json should be updated.
I guess there should be a command for that in NPM.

**Comment by benedekh** [comment]
The proposal by dependabot was to bump only the package-json, but I did not like that solution, because it seemed to be fragile. If someone deletes the package-lock.json in the future accidentally (or on purpose) and then recreates it then by the recreation it might happen that the vulnerable version of `braces` will be used by npm and not the one that is not vulnerable.

Alternatively, we could use the `resolutions` section of package.json and then we have to set the `braces` only there instead of both in `dependencies` and `devDependencies`.

**Comment by odzhychko** [comment]
Only updating the package-lock.json is the way to go.
The reason for the package-lock.json is to lock the dependencies.

The package-lock.json cannot be deleted accidentally because it is version controlled.
Nobody should just recreate it.
But even if someone recreates it and merges it, Dependabot would warn us about the vulnerabilities.

---

I think the way to go is to execute `npm audit fix` in the three repositories and commit the package-lock.json

**Comment by benedekh** [comment]
Okay, then I'll switch the approach and fix all conflicts that can be fixed. Probably it will also close https://github.com/modelix/modelix.samples/pull/288.

I will create a separate MR with the fix for all CVEs.

**Comment by benedekh** [comment]
Closing in favor of https://github.com/modelix/modelix.samples/pull/289

**Pull request closed without merging**
